language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: UbUbtAVGQ/gHQ6JYvzlHVMq4yeX/b7b0QlFQs6mAWRe5AKFCnvQOFStnPV0IH6ftTSpVQla3D5L6kUjchoB1C1XTV678aZKGw2VPsdQvoNvDHZEMGa5eFPBQHQm88cHIHO5FL8UmHMSegqBod6pFsZIwM+J2ykfZVSVrQGD86825/8AwLaDQT5bTFpL2lhLD9AgUzW1aUFrtq4QPOBRtbD7DYb3P6gFHRuDy07Jveuu1YreFBytkqjnNveOZBuKJmFkNFWN30YKcUfgTj3YYVXfLGnSsd1Ubv+oBAY2eCuZ9Ltw/H5w4Per3Bay1Ea1BqA5bqqW5EKXORRCazbF23d6vBbakr3M+0QWhWNyjq2QJ0besMPx5pHVBa34zWN76kRYoIR4T2rkz4ENYEf8WiGNRzXF50MnwBwo23okvLQSELCXqNY5lpAXrR8Uopew1FFjs11itVHRnm1CMzk6qmthvrFwKQUm0oCz32bRHDSniC5e/8t3cyRAqZyoqOCuYNi4BktXRuYudfKVDU7NBilYo5dDXNuvMZa7+BlGdldyAtLUPq9qvuI/mBZEkiN0th62n/0Xa9TUWYCZIaHAzQUGj4CzLtokT0ydIuhmxdrIJR/jJJekXGbB4oLEWwRfK2OxVh9/BrnE4XNmi3CRTGYSs1vDEdrxy2EOwYdjXcsk=
  app: moodsense
  on:
    repo: daSmith1105/mood-tracker-client
